### ISSUE TITLE
“将页面自动跳转到下一页。后文将介绍getWxPost.php的原理”

### ISSUE THREAD

**Issue by ichenfujun** [akinoneko/wechat-mq-spider#1]
请问这个功能是否能公开呢？
谢谢！

**Comment by akinoneko** [comment]
见https://github.com/akinoneko/wechat-mq-spider/blob/master/src/main/java/com/zyy/wechat/mq/spider/controller/SpiderController.java
中的**getWechatPost**方法

**Comment by ichenfujun** [comment]
再麻烦问一下：http://127.0.0.1:8080/spider这个服务源码方便公开吗？我想看一下结构，然后用python来实现一下。
谢谢！

**Comment by akinoneko** [comment]
这个项目开源的就是Spider服务的实现
